apiVersion: v1
kind: Service
metadata:
  name: ovpn
  namespace: ovpn
  labels:
    app: ovpn
spec:
  ports:
    - port: 1194
      targetPort: 1194
      protocol: UDP
      name: openvpn
  selector:
    app: ovpn
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ovpn
  namespace: ovpn
  labels:
    app: ovpn
    track: stable
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: openvpn
        app: ovpn
    spec:
      containers:
      - image: chepurko/docker-openvpn
        name: openvpn
        ports:
        - containerPort: 1194
          name: openvpn
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: ovpn0-key
          mountPath: /etc/openvpn/pki/private
        - name: ovpn0-cert
          mountPath: /etc/openvpn/pki/issued
        - name: ovpn0-pki
          mountPath: /etc/openvpn/pki
        - name: openvpn-conf
          mountPath: /etc/openvpn
        - name: ccd
          mountPath: /etc/openvpn/ccd
      volumes:
      - name: ovpn0-key
        secret:
          secretName: ovpn0-key
          defaultMode: 0600
      - name: ovpn0-cert
        secret:
          secretName: ovpn0-cert
      - name: ovpn0-pki
        secret:
          secretName: ovpn0-pki
          defaultMode: 0600
      - name: openvpn-conf
        configMap:
          name: openvpn-conf
      - name: ccd
        configMap:
          name: ccd
