apiVersion: v1
kind: Service
metadata:
  name: ovpn
  namespace: ovpn
  labels:
    app: ovpn
spec:
  ports:
    - port: 1194
      targetPort: 1194
      protocol: UDP
      name: openvpn
  selector:
    app: ovpn
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ovpn
  namespace: ovpn
  labels:
    app: ovpn
    track: stable
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: openvpn
        app: ovpn
    spec:
      containers:
      - image: kylemanna/openvpn
        name: openvpn
        ports:
        - containerPort: 1194
          name: openvpn
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: ovpn0-key
          mountPath: /etc/openvpn/pki/private
          readOnly: true
        - name: ovpn0-cert
          mountPath: /etc/openvpn/pki/issued
          readOnly: true
        - name: ovpn0-ca-crt
          mountPath: /etc/openvpn/pki
          readOnly: true
        - name: ovpn0-dh
          mountPath: /etc/openvpn/pki
          readOnly: true
        - name: ovpn0-ta
          mountPath: /etc/openvpn/pki
          readOnly: true
        - name: ovpn0-conf
          mountPath: /etc/openvpn
          readOnly: true
        - name: ovpn0-env
          mountPath: /etc/openvpn
          readOnly: true
        - name: ccd
          mountPath: /etc/openvpn
          readOnly: true
      volumes:
      - name: ovpn0-key
        secret:
          secretName: ovpn0-key
      - name: ovpn0-cert
        secret:
          secretName: ovpn0-cert
      - name: ovpn0-ca-crt
        secret:
          secretName: ovpn0-ca-crt
      - name: ovpn0-dh
        secret:
          secretName: ovpn0-dh
      - name: ovpn0-ta
        secret:
          secretName: ovpn0-ta
      - name: openvpn-conf
        configMap:
          name: openvpn-conf
      - name: ovpn-env
        configMap:
          name: ovpn-env
      - name: ccd
        configMap:
          name: ccd
