apiVersion: v1
kind: Service
metadata:
  name: ovpn
  namespace: ovpn
  labels:
    app: ovpn
spec:
  ports:
    - port: 1194
      targetPort: 1194
      protocol: UDP
      name: openvpn
  selector:
    app: ovpn
  type: LoadBalancer
---
