apiVersion: v1
kind: Service
metadata:
  name: ovpn
  namespace: ovpn
  labels:
    app: ovpn
spec:
  ports:
    - port: 1194
      targetPort: 1194
      protocol: UDP
      name: openvpn
  selector:
    app: ovpn
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ovpn-pv-claim
  namespace: ovpn
  labels:
    app: ovpn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # what's the minimum?
  storageClassName: slow
  selector:
    matchLabels:
      app: ovpn
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ovpn
  namespace: ovpn
  labels:
    app: ovpn
    track: stable
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: wp-nginx
        app: ovpn
    spec:
      containers:
      - image: kylemanna/openvpn
        name: openvpn
        ports:
        - containerPort: 1194
          name: openvpn
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.core.svc.cluster.local # this must be the FQDN of the mariadb Service
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass-ovpn
              key: mariadb-pass-ovpn.txt
        volumeMounts:
        - name: etc-openvpn
          mountPath: /etc/openvpn
      volumes:
      - name: etc-openvpn
        persistentVolumeClaim:
          claimName: ovpn-pv-claim
